### ISSUE TITLE
question: how to run it

### ISSUE THREAD

**Issue by akosglue** [Jsnhlbr5/Azul#4]
I have downloaded the zip file.
How do I run it?
I have tried 'javac Game.java' but it gives a few compilation errors.

**Comment by Jsnhlbr5** [comment]
If you're just trying to run it (not develop additions/changes), I would recommend downloading the release .jar instead; it's fully executable with just a JRE.
If you're sure you want to work from source, the main class is `view.Controller` in version 1.1

**Comment by Jsnhlbr5** [comment]
If you still have questions, please let me know.

**Comment by akosglue** [comment]
Thanks, I downloaded Eclipse and got it working. Nice. I played with it.
(I am implementing the same, but in PHP as a console app in order to practice TDD)
If you happen to work further on it, you could improve it by adding a kind of 'active' tile to see which tiles I have picked from a factory or in the middle. Sometimes I don't remember the color just before choosing a row.
